name: Deploy

on:
  push:
    branches:
      - production
      - alpha
      - beta

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # Will prevent the rest of the steps from running on fail
      - name: Check if user is a dialpad member
        uses: octokit/request-action@v2.1.0
        with:
          route: GET /orgs/{org}/members/{username}
          org: dialpad
          username: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.DIALTONE_CI_TOKEN }}

      - name: Set npm token
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.DIALTONE_NPM_TOKEN }}

      - name: Install dependencies
        run: npm run setup:ci

      - name: Build project
        run: npm run build

      - name: Deploy production
        if: ${BRANCH_NAME} == 'production'
        run: npm publish

      - name: Deploy prerelease
        if: ${BRANCH_NAME} != 'production'
        run: npm publish --tag ${BRANCH_NAME}
