name: Get dialtone-vue version

on:
  push:
    branches:
      - dt-vue-version

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      # Read dialtone-vue version number from package.json
      - name: get dialtone-vue version
        id: dialtone-vue-package-json
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: https://raw.githubusercontent.com/dialpad/dialtone-vue/release/package.json
          bearerToken: ${{ secrets.DIALTONE_CI_TOKEN }}
          method: GET

      - run: echo "${{ fromJSON(steps.dialtone-vue-package-json.outputs.response).version }}"
      - run: ls
      - run: sed -i 's/Vue-v0.0.0/Vue-v${{ fromJSON(steps.dialtone-vue-package-json.outputs.response).version }}/' docs/_site/index.html
      - run: cat docs/_site/index.html
